# Generated by Django 6.0.5 on 2026-06-01 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('starting_date', models.DateField(blank=True, null=True, verbose_name='Starting Date')),
                ('ending_date', models.DateField(blank=True, null=True, verbose_name='Ending Date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Game/Event Title')),
                ('date_time', models.DateTimeField(verbose_name='Date & Time')),
                ('venue', models.CharField(max_length=255, verbose_name='Venue')),
                ('grade', models.CharField(help_text='e.g. PL1, U18B1', max_length=100, verbose_name='Grade')),
                ('payment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Match Fee')),
                ('competitIon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='notebook.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='matches', to='notebook.role', verbose_name='Role(s)')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organiser Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notebook.organiser'),
        ),
        migrations.CreateModel(
            name='PaymentBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Payment Body Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_bodies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Bodies',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Payment Amount')),
                ('payment_status', models.CharField(choices=[('OUTSTANDING_REIMB', 'Reimbursement Outstanding'), ('OUTSTANDING', 'Outstanding'), ('PAID_REIMB', 'Reimbursement Paid'), ('PYMT_INDIV', 'Individual Payments'), ('PYMT_NONE', 'No Payment'), ('PAID', 'Paid')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='notebook.event')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='notebook.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('payment_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='notebook.paymentbody')),
            ],
        ),
        migrations.CreateModel(
            name='MatchOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Official Name')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officIals', to='notebook.match')),
                ('roles', models.ManyToManyField(blank=True, related_name='officials', to='notebook.role', verbose_name='Role(s)')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='events', to='notebook.role', verbose_name='Role(s)'),
        ),
    ]
