# Generated by Django 6.0.5 on 2026-06-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_rename_competition_match_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchofficial',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_official_entries', to='notebook.person'),
        ),
    ]
