# Generated by Django 6.0.5 on 2026-06-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_alter_matchofficial_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='Unnamed payment', max_length=255, verbose_name='Payment Name/Description'),
        ),
    ]
