# Generated by Django 6.0.5 on 2026-06-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Payment Name/Description'),
        ),
    ]
