# Generated by Django 6.0.5 on 2026-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_alter_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('OUTSTANDING_REIMB', 'Reimbursement Outstanding'), ('PAID_REIMB', 'Reimbursement Paid'), ('PYMT_INDIV', 'Individual Payments'), ('PYMT_NONE', 'No Payment'), ('PAID', 'Paid')], default=('OUTSTANDING', 'Outstanding'), max_length=20, verbose_name='Payment Status'),
        ),
    ]
