# Generated by Django 6.0.5 on 2026-06-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='badge_class',
            field=models.CharField(default='badge-ghost', help_text='DaisyUI color class: badge-primary, badge-secondary, badge-info, badge-success, etc.', max_length=50),
        ),
    ]
