# Generated by Django 6.0.5 on 2026-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0008_role_badge_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='match',
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='payments', to='notebook.event'),
        ),
        migrations.AddField(
            model_name='payment',
            name='match',
            field=models.ManyToManyField(blank=True, related_name='payments', to='notebook.match'),
        ),
    ]
