# Generated by Django 6.0.5 on 2026-06-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0009_remove_payment_event_remove_payment_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='event',
            new_name='events',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='match',
            new_name='matches',
        ),
    ]
