# Generated by Django 6.0.5 on 2026-06-14 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_rename_event_payment_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Base Match Fee'),
        ),
    ]
